Exousia/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

	path('admin/', admin.site.urls),
	url(r'', include('home.urls')),    
	url(r'account/', include('account.urls')),
	path(r'cart', include('cart.urls')),
	path('orders/', include('orders.urls')),
	path('Product/', include('Product.urls')),
	url(r'^oauth/', include('social_django.urls', namespace='social')),	
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

cart/urls.py
from django.conf.urls import url
from . import views
from orders.views import order_create
app_name = 'cart'

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<id>\d+)/$', views.cart_remove, name='cart_remove'),
	url(r'^create/$',order_create, name='order_create'),
]

home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.views import login
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'Home'
urlpatterns = [
	url(r'^$', views.Home.as_view(), name='index'),
    url(r'account/', include('account.urls'), name='account'),
    url(r'Product/', include('Product.urls'), name='Product'),
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from Product.models import Product, size

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26) ]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    sizes =forms.ModelMultipleChoiceField(queryset=size.objects.all(), to_field_name='name')

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.views.decorators.http import require_POST
from Product.models import Product
from .cart import Cart
from .forms import CartAddProductForm
# Create your views here.

@require_POST
def cart_add(request, id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'], sizes=cd['sizes'] )
	else:
		return HttpResponse(form.errors) 

	return redirect('cart:cart_detail')
	# return HttpResponse(cd['sizes'])

def cart_remove(request, id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=id)
	cart.remove(product)
	return redirect('cart:cart_detail')


def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'sizes':item['sizes'], 'update': True})
	return render(request, 'cart/detail.html', {'cart': cart})
	

cart/templates/cart/detail.html
{% extends 'home/base.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, Naira. {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
        <div class="table-responsive">
            <table class="table table-striped table-hover ">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>size</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{% if product.prod_image %} {{ product.prod_image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.prodname }}</td>
                            <td>
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>

                            <td>{{item.sizes}}</td>
                            <td>
                                <a href="{% url 'cart:cart_remove' product.id %}">Remove</a>
                            </td>
                            <td>kshs. {{ item.price }}</td>
                            <td>kshs. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>kshs. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        </div>
        <p class="text-right">
            <a href="{% url 'Home:index' %}" class="btn btn-default">Continue Shopping</a>
            <a href="{% url 'order_create' %}" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}