Exousia/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

	path('admin/', admin.site.urls),
	url(r'', include('home.urls')),    
	url(r'account/', include('account.urls')),
	path(r'cart', include('cart.urls')),
	path('orders/', include('orders.urls')),
	path('Product/', include('Product.urls')),
	url(r'^oauth/', include('social_django.urls', namespace='social')),	
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

Product/urls.py
from django.conf.urls import url,include
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import Prodcat,product_detail,GenderView, Catsort, genderCatSort,cate,Brand
from cart.views import cart_add
# from django.contrib.auth import views as auth_views

urlpatterns = [	
	url(r'^categories/(?P<pk>\d+)/$',Prodcat, name='category'),
	url(r'^brand/(?P<pk>\d+)/$',Brand, name='brand'),
	url(r'^gender/(?P<pk>\d+)/$',GenderView, name='Gender'),
	url(r'^category/(?P<gpk>\d+)/$',Catsort, name='cate'),	
	url(r'^product/(?P<pk>\d+)/$',product_detail , name='detail'),
	url(r'^ajax/category/(?P<cpk>\d+)/$',genderCatSort , name='sortcat'),
	url(r'^category/(?P<cat>\d+)/gender/(?P<pk>\d+)/$', cate, name='categories'),
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

cart/urls.py
from django.conf.urls import url
from . import views
from orders.views import order_create
app_name = 'cart'

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<id>\d+)/$', views.cart_remove, name='cart_remove'),
	url(r'^create/$',order_create, name='order_create'),
]

home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.views import login
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'Home'
urlpatterns = [
	url(r'^$', views.Home.as_view(), name='index'),
    url(r'account/', include('account.urls'), name='account'),
    url(r'Product/', include('Product.urls'), name='Product'),
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

home/models.py
from django.db import models

from django.conf import settings
# Create your models here.
class About(models.Model):
	name= models.CharField(max_length=20)
	logo = models.ImageField(upload_to='ammat/', default='me.png')
	about = models.TextField()
	phone = models.TextField()
	email = models.TextField()
	facebook= models.TextField()
	Twitter = models.CharField(max_length=20)
	youtube= models.TextField()

	def publish(self):
		self.save()

	def __str__(self):
		return self.name

home/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.views import generic
from Product.models import Product,categories,brand,Gender

# Create your views here.
class Home(generic.TemplateView):
	template_name= 'home/index.html'
	context_object_name = 'name'
	queryset = Product.objects.all()

	def get_context_data(self, **kwargs):
		context = super(Home, self).get_context_data(**kwargs)
		context['cate']= categories.objects.all()
		context['brand']= brand.objects.all()
		context['gender']= Gender.objects.all()		
		context['prod'] = self.queryset
		return context

class Base(generic.TemplateView):
	template_name= 'home/base.html'
	context_object_name = 'name'
	queryset = Product.objects.all()

	def get_context_data(self, **kwargs):
		context = super(Home, self).get_context_data(**kwargs)
		context['cate']= categories.objects.all()
		context['brand']= brand.objects.all()
		context['gender']= Gender.objects.all()		
		context['prod'] = self.queryset
		return context

home/templates/home/base.html
{% load static from staticfiles%}
<!DOCTYPE html>
<html>
  <head>
       <title>Exousia</title>
       <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>    
   </head> 
  

  <body style="padding-top:50px;">
  <div class="navbar navbar-default navbar-fixed-top">
      <div class="container" >
        <div class="navbar-header">
          <div class="nav navbar-brand">
           <a href="{% url 'Home:index' %}"><img src="{% static 'img/exousia 1.png' %}" style="width: 120px; height:50px;"></a>           
          </div>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>              
          </button>   
        </div> 
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="">Home</a></li>
              {% for gen in gender%}  
              <li>                
                <a href="{% url 'Home:Gender' pk=gen.pk  %}">{{gen.gender}}</a>
              </li>
              {% endfor %}
             <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="">Supplement<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Brand</a></li>
                  <li><a href="#">kilo</a></li>
                  <li><a href="#">seed</a></li>
                </ul>
             </li>
             <li>
             <form class="navbar-form" action="">
                    <div class="input-group img-responsive" >
                      <input type="text" class="form-control col-xs-12" placeholder="Search" name="search">
                        <div class="input-group-btn">
                          <button class="btn btn-danger" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                          </button> 
                        </div>
                    </div>
                </form></li> 
            </ul>
              <form class="navbar-form navbar-right">
                <center><div class="input-group">
                  <div class=" pull-right">
                    {% with totail_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a href="{% url 'cart:cart_detail' %}" class="quick-btn" >
                                <!--{{ totail_items }} item {{ totail_items|pluralize }}, naira. {{ cart.get_total_price }}-->
                                <img width="30px" height="30px" src="{% static 'img/basket-2.png' %}"><span class="label label-danger">{{ totail_items }}</span>

                                
                            </a>
                            {% else %}
                            <a href="{% url 'cart:cart_detail' %}"><img width="30px" height="30px" src="{% static 'img/basket-2.png' %}"></a>
                        {% endif %}
                    {% endwith %}
                 </div>
                </div></center>
              </form>
{% if user.is_authenticated%}
      <form class="navbar-form navbar-right">
        <center><div class="input-group">
      <p>Welcome {{user.username}} <a href="{% url 'logout' %}"><button type="button" class="btn btn-danger">Logout</button></a></p>
      </div></center>
      </form>
   {%else%}
  <form class="navbar-form navbar-right">
      <center><div class="input-group">
       <a href="{% url 'register' %}"><button type="button" class="btn btn-danger">
         Register
        </button></a>
        <a class="text-danger" href="{% url 'login' %}">Login</a> 
      </div></center>
    </form>
    {% endif %}
                
          </div>       
      </div>   
</div>

                {% block content%}

                {%endblock%}

<div id="footer" class="container-fluid">
    <div class="footerWrap ">
      <div id="footer1">
        Thank you for chosen us
      </div>
    </div>
    <div class="lookWrap">
      <div id="look">
        
        <div class="section">
          <h3>Support</h3>
          <a href="#">FAQs</a>
          <a href="#">Contact Us</a>
          <a href="#">Privacy Policy</a>
          <a href="#">Shipping Information</a>
          <a href="#">Return Policy</a>
          <a href="#">Item Exchange</a>
          <a href="#">Cash Back Rewards</a>
        </div>
        <div class="section">
          <h3>Give & Take</h3>
          <a href="#">Gift Certificates</a>
          <a href="#">Wishlist</a>
          <a href="#">Gift Ideas</a>
          <a href="#">Refer a Friend</a>
          <a href="#">Reviews</a>
          <a href="#">Scholarship</a>
          <a href="#">Sponsor</a>
        </div>
        <div class="section">
          <h3>Follow Us</h3>
          <a href="#">Facebook</a>
          <a href="#">Twitter</a>        
          <a href="#">Pinterest</a>
          <a href="#">Blog</a>
          <a href="#">Ravelry</a>
          <a href="#">Sponsor</a>
          <a href="#">RSS</a>
        </div>
        <div class="section">
          <h3>About Us</h3>
          <a href="#">About</a>
          <a href="#">Contact us</a>      
          <a href="#">The Team</a>        
        </div> 
        <div class="section cardsec">
         <a herf="#"><img src="{% static 'img/card_1.jpg' %} "></a>
         <br>
         <a herf="#"><img src="{% static 'img/card_2.jpg' %} "></a>
         <br>
         <a herf="#"><img src="{% static 'img/card_3.jpg' %} "></a>
         <br>
         <a herf="#"><img src="{% static 'img/card_4.jpg' %} "></a>
          
        </div>     
      </div>
    </div>
    <div class="legality">
          © Copyright 2017 Exousia.
        </div>
  
</div>
</body>
{% block javascript%}

{% endblock %}
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

home/templates/home/index.html
{% extends 'home/base.html'%}
{% load static from staticfiles%}

{% block content %}
      
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox" >
    <div class="item active">
      <img src=" {% static 'img/slide001.png' %} " alt="Chania">
    </div>

    <div class="item">
      <img src=" {% static 'img/slide002.png' %} " alt="Chania">
    </div>

    <div class="item">
      <img src="{% static 'img/slide002.png' %}" alt="Flower">
    </div>

    <div class="item">
      <img src=" {% static 'img/slide004.png' %} " alt="Flower">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
        
	    <div class="container">
             <h2 style="color:black; text-align:center; font-weight:bold; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">New Arrivals/Sale</h2>
      </div>

  <br>
    <div class="container">
    <div class="row">
    	{% for cat in cate %}
      <div class="col-md-4 col-xs-12">
        <div class="colbox1">      
          <img src="{{cat.catImage.url}}" alt="adidas" style="width:100%; height:100%;" class="img-responsive">
              <p class="titlecol">{{cat.catname}}</p>
                <div class="button"><a href="{% url 'Home:category' pk=cat.pk  %}">VIEW</a></div>
        </div>
      </div>{% endfor %}
    </div>    
  </div>
	

      <div class="container">
        <h2 style=" color: black; text-align:center; font-weight:bold; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
          Shop by Brand
        </h2>

      </div>
	<div class="container">
	  <div class="row box">
	  	{% for brands in brand %}
	      <center><div class="col-md-3 col-xs-12" style="margin-bottom:40px">
	        <a href="{% url 'Home:brand' pk=brands.pk  %}">
	          <img id="imgset" src="{{brands.brand_logo.url}}" style="height:50px;">
	        </a>
	      </div></center>
	     {% endfor %} 	      
	  </div>
	</div>

	<!--<h1>Brands</h1>
		<h2>{{brands.brand_name}}</h2>
		<img width=10% height=10% src="{{brands.brand_logo.url}}" alt="IMG-PRODUCT"> -->
	

	<!--<h1>Products</h1>
	{% for product in prod %}
		<a href="{% url 'Home:detail' product.pk %}"><h2>{{product.prodname}}</h2></a>
		<img width=30% height=30% src="{{product.prod_image.url}}" alt="IMG-PRODUCT">
		<a href=""><p>Brand: {{product.brand}}</p></a>
		<a href=""><p>Gender: {{product.gender}}</p></a>
	{% endfor %}-->

{% endblock %}
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script> 

home/templates/home/index2.html
{% load static from staticfiles%}
<!DOCTYPE html>
<html>
   <head>
       <title>Exousia</title>
       <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  <script src="{% static 'js/jquery.js' %}"></script>    
   </head> 
  

  <body>
  <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <div class="nav navbar-brand">
           <a href="#"><img src="img/exousia 1.png" style="width: 120px; height:50px;"></a>           
          </div>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>              
          </button>   
        </div> 
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="">Home</a></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Men
                  <span class="caret"></span></a> 
                  <ul class="dropdown-menu">            
                    <li><a href="#">Accessories</a></li>
                    <li><a href="#">Clothing</a></li> 
                    <li><a href="#">Shoes</a></li> 
                    <li><a href="#">Trending Now</a></li> 
                  </ul>
              </li>
             <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Women<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Accessories</a></li>
                <li><a href="#">Bags</a></li>
                <li><a href="#">Clothing</a></li>
                <li><a href="#">Shoes</a></li>
                <li><a href="#">Trending Now</a></li>
              </ul>
             </li> 
             <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="">Supplement<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Brand</a></li>
                  <li><a href="#">kilo</a></li>
                  <li><a href="#">seed</a></li>
                </ul>
             </li> 
            </ul>
              <form class="navbar-form navbar-right">
                <div class="">
                  <button class="btn btn-info pull-right">
                    {% with totail_items=cart|length %}
                        {% if cart|length > 0 %}
                            My Shopping Order:
                            <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                                {{ totail_items }} item {{ totail_items|pluralize }}, naira. {{ cart.get_total_price }}
                            </a>
                            {% else %}
                            <a href="{% url 'cart:cart_detail' %}">Cart</a>
                        {% endif %}
                    {% endwith %}
                 </button>
                </div>
              </form>
                {% if user.is_authenticated%}
                  <form class="navbar-form navbar-right">
                  <p>Welcome {{user.username}}</p>
                  <a href="{% url 'logout' %}"><button type="button" class="btn btn-danger">Logout</button></a>
                  </form>
               {%else%}
              <form class="navbar-form navbar-right">
                  <div class="">
                   <a href="{% url 'register' %}"><button type="button" class="btn btn-danger">
                     Register
                    </button></a>
                    <a href="{% url 'login' %}">Login</a> 
                  </div>
                </form>
                {% endif %}
                <form class="navbar-form navbar-right" action="">
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Search" name="search">
                        <div class="input-group-btn">
                          <button class="btn btn-danger" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                          </button> 
                        </div>
                    </div>
                </form>
          </div>       
      </div>   
</div>

    <div class="container-fluid">  
        <div id="myCarousel" class="img-responsive carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
          </ol>
      
          <!-- Wrapper for slides -->
        
          <div class="carousel-inner">
            <div class="item active" style="height:500px;">
              <img class="img-responsive" src="img/slide001.png" alt="Shop now" style="width:100%;">
            </div>
      
            <div class="item" style="height:500px;">
              <img class="img-responsive" src="img/slide004.png" alt="" style="width:100%;">
            </div>
          
            
            <div class="item" style="height:500px;">
              <img class="img-responsive" src="img/slide002.png" alt="" style="width:100%;">
            </div>

            <div class="item" style="height:500px;">
              <img class="img-responsive" src="img/slide2.jpg" alt="" style="width:100%;">
            </div>
          </div>
      
          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

      <br>

    <div class="container">
             <h2 style="color:black; text-align:center; font-weight:bold; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">New Arrivals/Sale</h2>
      </div>

      <br>
    <div class="container">
      <div class="row">
          <div class="col-md-4">
            <div class="col-md-12 colbox1">
              <img src="img/sale.png" style="height:40px;">
              <h1 style="font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; font-weight:bolder; color: rgb(255, 123, 0);">{{cat.catname}}</h1>
            </div>
          </div>

          <div class="col-md-4">
            <div class="col-md-12 colbox2">
                <img src="img/sale.png" style="height:40px;">
              <h2 style="font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; font-weight:bolder; color: rgb(255, 123, 0);">Clothes</h2>

            </div>
          </div> 

          <div class="col-md-4">
              <div class="col-md-12 colbox3">
                  <img src="img/sale.png" style="height:40px;">
                <h2 style="font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; font-weight:bolder; color: rgb(255, 123, 0);">Accessories</h2>
              </div>
  
            </div>
      </div>        
    </div>

      <br>
      <div class="container">
        <h2 style="color:black; text-align:center; font-weight:bold; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
          Shop by Brand
        </h2>

      </div>
<div class="container">
  <div class="row box">
      <div class="col-md-3 ">
        <a href="">
          <img id="imgset" src="img/tommy.jpg" style="height:50px;">
        </a>
      </div>
    
      <div class="col-md-3 ">
        <a href="">
          <img id="imgset" src="img/levis.png" style="height:50px;">
        </a>
      </div>
    
      <div class="col-md-3 ">
        <a href="">
          <img id="imgset" src="img/Lacoste-logo-1933.png" style="height:50px;">
        </a>
      </div>
       
      <div class="col-md-3 ">
        <a href="">
          <img id="imgset" src="img/Champion-Company-Logo-Image.jpg" style="height:50px;">
        </a>
      </div>
      
  </div>    

  <div class="row box">
      <div class="col-md-2 ">
        <a href="">
          <img id="imgset" src="img/puma.jpg" style="height:50px;">
        </a>
      </div>
    
      <div class="col-md-2 ">
        <a href="">
          <img id="imgset" src="img/versace.jpg" style="height:50px;">
        </a>
      </div>
    
      <div class="col-md-2 ">
        <a href="">
          <img id="imgset" src="img/Reebok-logo.jpg" style="height:50px;">
        </a>
      </div>
       
      <div class="col-md-2 ">
        <a href="">
          <img id="imgset" src="img/nike-clip-art-Nike.gif" style="height:50px;">
        </a>
      </div>
      
      <div class="col-md-2 ">
        <a href="">
          <img id="imgset" src="img/gucci.jpg" style="height:50px;">
        </a>
      </div>

      <div class="col-md-2 ">
        <a href="">
          <img id="imgset" src="img/calvinklein.jpg" style="height:50px;">
        </a>
      </div>
    
  </div>   
  
  <div class="row box">
      <div class="col-md-2 ">
        <a href="">
          <img id="imgset" src="img/Dolce__Gabbana.png" style="height:50px;">
        </a>
      </div>
    
      <div class="col-md-2 ">
        <a href="">
          <img id="imgset" src="img/channel.jpg" style="height:50px;">
        </a>
      </div>
    
      <div class="col-md-2 ">
        <a href="">
          <img id="imgset" src="img/adidas-logo.gif" style="height:50px;">
        </a>
      </div>   
    
  </div>    
</div>

<div id="footer" class="container-fluid">
    <div class="footerWrap ">
      <div id="footer1">
        Thank you for chosen us
      </div>
    </div>
    <div class="lookWrap">
      <div id="look">
        
        <div class="section">
          <h3>Support</h3>
          <a href="#">FAQs</a>
          <a href="#">Contact Us</a>
          <a href="#">Privacy Policy</a>
          <a href="#">Shipping Information</a>
          <a href="#">Return Policy</a>
          <a href="#">Item Exchange</a>
          <a href="#">Cash Back Rewards</a>
        </div>
        <div class="section">
          <h3>Give & Take</h3>
          <a href="#">Gift Certificates</a>
          <a href="#">Wishlist</a>
          <a href="#">Gift Ideas</a>
          <a href="#">Refer a Friend</a>
          <a href="#">Reviews</a>
          <a href="#">Scholarship</a>
          <a href="#">Sponsor</a>
        </div>
        <div class="section">
          <h3>Follow Us</h3>
          <a href="#">Facebook</a>
          <a href="#">Twitter</a>        
          <a href="#">Pinterest</a>
          <a href="#">Blog</a>
          <a href="#">Ravelry</a>
          <a href="#">Sponsor</a>
          <a href="#">RSS</a>
        </div>
        <div class="section">
          <h3>About Us</h3>
          <a href="#">About</a>
          <a href="#">Contact us</a>      
          <a href="#">The Team</a>        
        </div> 
        <div class="section cardsec">
         <a herf="#"><img src="img/card_1.jpg"></a>
         <br>
         <a herf="#"><img src="img/card_2.jpg"></a>
         <br>
         <a herf="#"><img src="img/card_3.jpg"></a>
         <br>
         <a herf="#"><img src="img/card_4.jpg"></a>
          
        </div>     
      </div>
    </div>
  
    <div class="legality">
          © Copyright 2017 Exousia.
        </div>
  
</div>
   </body>
   <script type="text/javascript" src="js/bootstrap.min.js"></script>
</html>