Exousia/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

	path('admin/', admin.site.urls),
	url(r'', include('home.urls')),    
	url(r'account/', include('account.urls')),
	path(r'cart', include('cart.urls')),
	path('orders/', include('orders.urls')),
	path('Product/', include('Product.urls')),
	url(r'^oauth/', include('social_django.urls', namespace='social')),	
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

cart/urls.py
from django.conf.urls import url
from . import views
from orders.views import order_create
app_name = 'cart'

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<id>\d+)/$', views.cart_remove, name='cart_remove'),
	url(r'^create/$',order_create, name='order_create'),
]

orders/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    # url(r'^created/$', views.created.as_view(), name='order_created'),
    url(r'^lga/$', views.loadLga, name='load_lga'),
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

orders/models.py
from django.db import models
from Product.models import Product, States,Lga


class Order(models.Model):
	first_name = models.CharField(max_length=60)
	last_name = models.CharField(max_length=60)
	email = models.EmailField()   
	state = models.ForeignKey(States, on_delete=models.CASCADE)
	lga = models.ForeignKey(Lga, on_delete=models.CASCADE)
	address = models.CharField(max_length=150)
	postal_code = models.CharField(max_length=30)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	paid = models.BooleanField(default=False)

	class Meta:
		ordering = ('-created', )

	def __str__(self):
		return 'Order {}'.format(self.id)

	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
	order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
	product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(default=1)

	def __str__(self):
		return '{}'.format(self.id)

	def get_cost(self):
		return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order,Lga


class OrderCreateForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'state','lga']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['lga'].queryset = Lga.objects.all()

orders/views.py
from django.shortcuts import render
from .models import OrderItem,Lga
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity'],
                    size=item['sizes'],
                )
            cart.clear()
        return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'form': form})
    
def loadLga(request):
	state_id = request.GET.get('state')
	lga = Lga.objects.filter(state_id=state_id).order_by('lga')
	return render(request, 'orders/lga.html', {'lga':lga})

orders/templates/orders/order/create.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}
{% load crispy_forms_tags %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block content %}
    <div class="container">
        <div class="container" style="margin-top: 6%">
            <div class="col-md-4">
                <h4 class="page-header">Checkout</h4>
                <form action="." class="form-horizontal" method="post" id="orderForm" data-lga-url="{% url 'load_lga'%}">
                    {% csrf_token %}
                    <div class="form-group">
                    {{ form|crispy }}
                    </div>

                    <input type="submit" class="btn btn-primary" value="Submit order">
                </form>
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-4">
                <div class="page-header">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }}x {{ item.product.name }}
                        <span>Naira. {{ item.total_price }}</span><span>{{item.sizes}}</span>
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Total Cost: Naira. {{ cart.get_total_price }}</li>
                </ul>

            </div>
        </div>
    </div>
{% endblock %}
{% block javascript%}
 <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="crossorigin="anonymous"></script>
  <script>
    $("#id_state").change(function () {
      var url = $("#orderForm").attr("data-lga-url");  // get the url of the `load_cities` view
      var stateID = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'state': stateID       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_lga").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>
  {%endblock%}

orders/templates/orders/order/created.html
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8 col-md-offset-2">
                <h3 class="page-header">Thank You For Shopping With Us
                </h3>
                <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
            </div>
        </div>
    </div>
{% endblock %}