Exousia/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

	path('admin/', admin.site.urls),
	url(r'', include('home.urls')),    
	url(r'account/', include('account.urls')),
	path(r'cart', include('cart.urls')),
	path('orders/', include('orders.urls')),
	path('Product/', include('Product.urls')),
	url(r'^oauth/', include('social_django.urls', namespace='social')),	
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

Product/urls.py
from django.conf.urls import url,include
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import Prodcat,product_detail,GenderView, Catsort, genderCatSort,cate,Brand
from cart.views import cart_add
# from django.contrib.auth import views as auth_views

urlpatterns = [	
	url(r'^categories/(?P<pk>\d+)/$',Prodcat, name='category'),
	url(r'^brand/(?P<pk>\d+)/$',Brand, name='brand'),
	url(r'^gender/(?P<pk>\d+)/$',GenderView, name='Gender'),
	url(r'^category/(?P<gpk>\d+)/$',Catsort, name='cate'),	
	url(r'^product/(?P<pk>\d+)/$',product_detail , name='detail'),
	url(r'^ajax/category/(?P<cpk>\d+)/$',genderCatSort , name='sortcat'),
	url(r'^category/(?P<cat>\d+)/gender/(?P<pk>\d+)/$', cate, name='categories'),
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

cart/urls.py
from django.conf.urls import url
from . import views
from orders.views import order_create
app_name = 'cart'

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<id>\d+)/$', views.cart_remove, name='cart_remove'),
	url(r'^create/$',order_create, name='order_create'),
]

home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.views import login
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
app_name = 'Home'
urlpatterns = [
	url(r'^$', views.Home.as_view(), name='index'),
    url(r'account/', include('account.urls'), name='account'),
    url(r'Product/', include('Product.urls'), name='Product'),
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

Product/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# Create your models here.

class size(models.Model):
	"""
	Description: Model Description
	"""
	name= models.CharField(max_length=10)
	tag=models.CharField(max_length=3)

	def publish(self):
		self.save()

	def __str__(self):
		return self.name

class categories(models.Model):
	categories = models.CharField(max_length=20, null=True)
	catname = models.CharField(max_length=20)
	catImage = models.ImageField(upload_to='category', default='me.png')
	shelve = models.ImageField(upload_to='category/shelve', default='me.png')
	slug = models.SlugField(max_length=200,unique=True)
	# product = models.ManyToManyField(Product)
	def publish(self, *args, **kwargs):
		self.slug = slugify(self.catname)
		super(categories,self).save(*args, **kwargs)

	def __str__(self):
		return self.catname	

# class subCat(models.Model):
# 	sub_cat = models.CharField(max_length=20, null=True)
# 	subCatName = models.CharField(max_length=20)
# 	slug = models.SlugField(max_length=200,unique=True)
# 	# product = models.ManyToManyField(Product)
# 	def publish(self, *args, **kwargs):
# 		self.slug = slugify(self.sub_cat)
# 		super(subCat,self).save(*args, **kwargs)

# 	def __str__(self):
# 		return self.sub_cat	

class brand(models.Model):
	"""
	Description: Model Description
	"""
	brand_name= models.CharField(max_length=20)
	brand_logo= models.ImageField(upload_to='media/product/brands')
	brand_image = models.ImageField(upload_to='media/product/brands', default='me.png')
	def publish(self):
		self.save()

	def __str__(self):
		return self.brand_name

class Gender(models.Model):
	"""
	Description: Model Description
	"""
	gender= models.CharField(max_length=10)
	tags= models.CharField(max_length=1)
	gender_image = models.ImageField(upload_to='gender', default='default.png')
	description=models.TextField(default='gender')
	category= models.ManyToManyField(categories, blank=True)
	
	def publish(self):
		self.save()

	def __str__(self):
		return self.gender


class Product(models.Model):
	"""
	Description: Model Description
	"""
	prod_image = models.ImageField(upload_to='image/products/')
	rearImage= models.ImageField(upload_to='image/products/', default='default.png', blank=True)
	frontImage= models.ImageField(upload_to='image/products/', default='default.png', blank=True)
	categories = models.ForeignKey(categories, on_delete=models.DO_NOTHING, blank=True, default=1)
	# sub_cat = models.ForeignKey(subCat, on_delete=models.DO_NOTHING, blank=True, default=1)
	prodname = models.CharField(max_length=30, help_text='max of 30 characters')
	price = models.FloatField()
	sizes = models.ManyToManyField(size)
	numbers = models.PositiveIntegerField()
	description = models.TextField()
	weight= models.FloatField()
	Dimension= models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	material = models.CharField(max_length=10)
	brand= models.ForeignKey(brand, on_delete=models.DO_NOTHING)
	gender= models.ForeignKey(Gender,on_delete=models.DO_NOTHING, default=1)

	def publish(self):
		self.save()

	def __str__(self):
		return self.prodname

class States(models.Model):
	"""
	Description: Model Description
	"""
	state= models.CharField(max_length=50)
	def publish(self):
		self.save()

	def __str__(self):
		return self.state

class Lga(models.Model):
	lga = models.CharField(max_length=50)
	state = models.ForeignKey(States, on_delete=models.DO_NOTHING)
	def publish(self):
		self.save()

	def __str__(self):
		return self.lga

class cart(models.Model):
	product =  models.ForeignKey(Product, on_delete=models.DO_NOTHING)
	quantity = models.IntegerField(default=1)
	total = models.IntegerField(default=1)
	subtotal= models.IntegerField(default=1)
	shipping= models.FloatField()
	state = models.ForeignKey(States, on_delete=models.DO_NOTHING)
	lga = models.ForeignKey(Lga, on_delete=models.DO_NOTHING)

	def calc_total(self):
		total = quantity * product.price
		return total

	def publish(self):
		self.save()

	def __str__(self):
		return self.product

Product/forms.py
from django import forms
from .models import Product

class itemForm(forms.ModelForm):
	class Meta:
		model= Product
		fields=['sizes',]
		widgets = {
			'sizes': forms.Select()
		}

Product/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import categories, Product,Gender,brand
from django.views import generic
from cart.forms import CartAddProductForm
from django.http import JsonResponse
import json
# Create your views here.


def Prodcat(request, pk):
	template= 'Product/prodcat.html'
	category = get_object_or_404(categories, pk=pk)
	gender = Gender.objects.all()
	product = Product.objects.filter(categories=category)

	context = {
	'category': category,
	'gender':gender,
	'product': product,
	}
	return render(request, template, context)

def cate(request,pk,cat):
	template= 'Product/gender.html'
	gender= Gender.objects.all()
	gens= get_object_or_404(Gender, pk=pk)
	category=get_object_or_404(categories, pk=cat)
	cat= categories.objects.all()
	product = Product.objects.filter(gender=gens, categories=category )
	
	context = {
	# 'category': category,
	'gens': gens,
	'gender':gender,
	'product': product,
	'cat': cat,
	'category':category,
	}
	return render(request, template, context)
	

def Brand(request, pk):
	template= 'Product/brand.html'
	brands = get_object_or_404(brand, pk=pk)
	product = Product.objects.filter(brand=brands)
	gender = Gender.objects.all()
	shoes = Product.objects.filter(brand=brands, categories__categories='Shoes')
	accessories = Product.objects.filter(brand=brands, categories__categories='Accessories')
	wears = Product.objects.filter(brand=brands, categories__categories='Wears')
	context = {
	'brands': brands,
	'product': product,
	'gender': gender,
	'wears' :wears, 
	'accessories': accessories,
	'shoes':shoes,
	}
	return render(request, template, context)

# def genderView(request, pk, gpk):
# 	template= 'Product/gender.html'
# 	gend = get_object_or_404(gender, pk=pk)
# 	category = get_object_or_404(categories, pk=gpk)
# 	product = Product.objects.filter(gender=gender).annotate(categories=category)

# 	context = {
# 	'gend': gend,
# 	'product': product,
# 	'category': category,
# 	}
# 	return render(request, template, context)

def GenderView(request, pk):
	template= 'Product/gender.html'
	# category = get_object_or_404(categories, pk=pk)
	gender= Gender.objects.all()
	gens= get_object_or_404(Gender, pk=pk)
	product = Product.objects.filter(gender=gens)
	cat=categories.objects.all()
	context = {
	# 'category': category,
	'gens': gens,
	'gender':gender,
	'product': product,
	'cat': cat,
	
	}
	return render(request, template, context)

def genderCatSort(request,cpk):
	cat_id = get_object_or_404(categories, pk=cpk)
	gend_id = request.GET.get('gender')
	produ = Product.objects.filter(categories=cat_id, gender__gender=gend_id).order_by('prodname')
	context={
		'produ':produ,
		'cat_id':cat_id,
	}
	return render(request, 'Product/catsort.html',context)

def images(request):
	img = request.GET.get('src')


def Catsort(request,gpk):
	template='Product/gender.html'
	category=get_object_or_404(categories, pk=pk)
	prods= Product.objects.filter(categories=category)

	context={
	'category':category,
	'prods':prods,
	}
	return render(request, template, context)

def FemaleView(request, pk):
	template= 'Product/gender.html'
	cat= categories.objects.all()
	category = get_object_or_404(categories, pk=pk)
	gen= gender.objects.get(gender="Female")	
	product = Product.objects.filter(gender__gender="Female", categories=category)

	context = {
	'category': category,
	'gen':gen,
	'product': product,
	'cat': cat,
	}
	return render(request, template, context)

class DetailView(generic.DetailView):
	model = Product
	template_name = 'Product/product.html'

def product_detail(request, pk):
	product = get_object_or_404(Product, pk=pk)
	item = CartAddProductForm()
	gender = Gender.objects.all()
	context = {
		'product': product,
		'item': item,
		'gender': gender,
	}
	return render(request, 'Product/product.html', context)

Product/templates/Product/brand.html
{% extends 'home/base.html'%}
{% load static from staticfiles%}

{% block content %}

<div class="smooth">
<div class="container-fluid"> 
  <div class="row">
      <div class="nikebrandwall1"> 
        <img class="img-responsive" src="{{brands.brand_image.url}}">
        <div class="dropbut">
        <p>Shop Now</p>
        <a href="#items">
          <center><i class="glyphicon glyphicon-menu-down"></i></center>
        </a></div>
      </div> 
  </div>     
</div>
<br>
<center>
  <div id="items" class="niketext">
    <h3 style="font-weight:700;">IMPOSSIBLE AIR</h3>
    <p>Make shoe Contact before eye contact<br> Nike Air  2019 'Space Walk'</p>
  </div>
</center>

<br>
<!--shop/wears/accessories-->

<div  class="container-fluid"> 
  <h1 style="color: rgb(0, 0, 0); font-family: 'Times New Roman', Times, serif;">Shoes</h1>
  <div style="border:rgb(73, 73, 73) solid 1px;" class="border"></div>
  <br>
  <div class="row">
        {% for shoe in shoes %}
                  <div class="col-md-3">
                      <div class="col-md-12">
                          <div style="background-color:rgb(255, 255, 255);">
                           <a href="{% url 'Home:detail' shoe.pk %}"><img class="overlay img-responsive" src="{{ shoe.prod_image.url}}" alt="short"></a>
                          </div>
                      <span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-weight: bold; 
                      font-size:25px;"> {{shoe.prodname}}</span>
                      <br>
                        <h4>{{shoe.price}}</h4>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                        
        
                      </div>
                    </div>
      {% endfor %}
  
</div>
</div>
<br>
<br>
<br>

<center>
  <div class="niketext">
    <h3 style="font-weight:700;">IMPOSSIBLE AIR</h3>
    <p>Make shoe Contact before eye contact<br> Nike Air  2019 'Space Walk'</p>
  </div>
</center>
<div class="container-fluid">
  <h1 style="color: rgb(0, 0, 0); font-family: 'Times New Roman', Times, serif;">Wears</h1>
  <div style="border:rgb(73, 73, 73) solid 1px;" class="border"></div>
  <br>
  <div class="row">
      {% for wear in wears %}
                  <div class="col-md-3">
                      <div class="col-md-12">
                          <div style="background-color:rgb(255, 255, 255);">
                           <a href="{% url 'Home:detail' wear.pk %}"><img class="overlay img-responsive" src="{{ wear.prod_image.url}}" alt="short"></a>
                          </div>
                      <span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-weight: bold; 
                      font-size:25px;"> {{wear.prodname}}</span>
                      <br>
                        <h4>{{wear.price}}</h4>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                        
        
                      </div>
                    </div>
      {% endfor %}
  
</div>
</div>
<br>
<br>
<br>
<center>
  <div class="niketext">
    <h3 style="font-weight:700;">IMPOSSIBLE AIR</h3>
    <p>Make shoe Contact before eye contact<br> Nike Air  2019 'Space Walk'</p>
  </div>
</center>

<div class="container-fluid">
    <h1 style="color: rgb(0, 0, 0); font-family: 'Times New Roman', Times, serif;">Accessories</h1>
    <div style="border:rgb(73, 73, 73) solid 1px;" class="border"></div>
    <br>
    <div class="row">
        {% for access in accessories %}
                  <div class="col-md-3">
                      <div class="col-md-12">
                          <div style="background-color:rgb(255, 255, 255);">
                           <a href="{% url 'Home:detail' access.pk %}"><img class="overlay img-responsive" src="{{ access.prod_image.url}}" alt="short"></a>
                          </div>
                      <span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-weight: bold; 
                      font-size:25px;"> {{access.prodname}}</span>
                      <br>
                        <h4>{{access.price}}</h4>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                        
        
                      </div>
                    </div>
        {% endfor %}
    
</div>
</div>
<!--/shoes/wears/accessories-->
<!--<div class="container">
    <div class="row">
    
        <div class="col-md-4">
            <div class="brandcol">
                <img src="img/naija.jpg" style="height:100%; width:100%;">
            </div>
            
        </div>

        <div class="col-md-4">
                <div class="brandcol1">
                    <img src="img/whiteshoe.jpg" style="height:100%; width:100%;">
                </div>
                   
            </div>

   
    </div>
</div>
-->
</div>

{% endblock %}

Product/templates/Product/catsort.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h3 style="font-weight:bold; font-family: sans-serif; border-bottom: rgb(155, 56, 56) 1px solid;"> {{cat_id.catname}} </h3>
	{% for pros in produ %}

           <div class="col-md-4">
              <div class="col-md-12">
                          <div style="background-color:rgb(255, 255, 255);">
                           <a href="{% url 'Home:detail' pros.pk %}"><img class="overlay img-responsive" src="{{ pros.prod_image.url}}" alt="short";></a>
                          </div>
                  <span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-weight: bold; 
                  font-size:25px;">{{pros.prodname}}</span>
                  <br>
                    <h4>{{pros.price}}</h4>
                      <span class="glyphicon glyphicon-star"> </span>
                      <span class="glyphicon glyphicon-star"> </span>
                      <span class="glyphicon glyphicon-star"> </span>
              </div>                  
           </div>
    {% endfor %}
</body>
</html>

Product/templates/Product/gender.html
{% extends 'home/base.html'%}
{% load static from staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/w3.css'%}">
{% block content%}
<div style="	position: relative;		height: 500px;	width: 100%;">
      <img class="img-responsive" src="{{gens.gender_image.url}}" style="width:100%; height:500px;">
      <div class="col-md-6 col-sm-6 col-xs-6 top-left"><h4 style="text-align:left; font-size:90px; font-family: cursive; padding:0px 0px 0px 0px;">{{gens.gender}}</h4>
		<h2 id="menid" style="text-align:left; font-family: cursive;">{{gens.description}}</h2> 
      </div>
      
    
</div>

<br>
<br>  
<div class="container" >
  <div class="row" >
    <div class="col-md-2 col-xs-4" style="border-right:rgb(155, 56, 56) 1px solid;">
          <h4 style="text-align:center;">Shop by Category</h4>         
          <div class="list-group" >
              {% for cate in cat %}
  <a href="#prod" class="catgend list-group-item" data-cats="{{cate.catname}}" data-gen="{{gens.gender}}" data-sort-url="{% url 'Home:sortcat' cpk=cate.pk %}" >{{cate.catname}}</a>
{% endfor %}
            </div>
    </div>
<!--<a class="likebutton" id="like{{post.id}}" href="#" data-catid="{{ post.id }}">Like</a>-->
        <div class="col-md-10 col-xs-8">
           <div id="products">
            <div class="progress">
              <img src="{% static 'img/load.gif' %}">
            </div>
            <h3 style="font-weight:bold; font-family: sans-serif; border-bottom: rgb(155, 56, 56) 1px solid;"> All </h3>
           	{% for pro in product%}
                  <div class="col-md-4">
                      <div class="col-md-12">
                          <div style="background-color:rgb(255, 255, 255);">
                           <a href="{% url 'Home:detail' pro.pk %}"><img class="overlay img-responsive" src="{{ pro.prod_image.url}}" alt="short"></a>
                          </div>
                      <span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-weight: bold; 
                      font-size:25px;"> {{pro.prodname}}</span>
                      <br>
                        <h4>{{pro.price}}</h4>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                        
        
                      </div>                  
                  </div>
             {%endfor%}
           </div>   
            </div> 
          </div>       
        </div>
  </div>  
</div>
{% endblock%}
{% block javascript%}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>    
<script type="text/javascript">
  $('.progress').hide();
  $('.catgend').on('click', function (e) {
    $('.progress').show()
    var data = $(this).data()
    $.ajax({                       
        url: data.sortUrl,                    
        data: {
            'cat': data.cats,
            'gender': data.gen,     
        },
        success: function (data) {   
            $('#products').html(data);
            $('.progress').hide()  
        }
    });
    
});
</script>
{%endblock %}

Product/templates/Product/genders.html
 {% load static from staticfiles %}
              {% for cate in cat %}
  <a href="#" class="catgend" data-cats="{{cate.catname}}" data-gen="{{gens.gender}}" data-sort-url="{% url 'Home:sortcat' cpk=cate.pk %}" >{{cate.catname}}</a>
{% endfor %}
              <div id="products">
{% for pro in product%}
                  <div class="col-md-4">
                      <div class="col-md-12">
                          <div style="background-color:rgb(255, 255, 255); height:280px;">
                           <a href="{% url 'Home:detail' pro.pk %}"><img class="overlay" src="{{ pro.prod_image.url}}" alt="short" style="width:100%; height:100%;"></a>
                          </div>
                      <span style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-weight: bold; 
                      font-size:25px;"> {{pro.prodname}}</span>
                      <br>
                        <h4>{{pro.price}}</h4>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                          <span class="glyphicon glyphicon-star"> </span>
                        
        
                      </div>                  
                  </div>
             {%endfor%}
              </div>



<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript">
	$('.catgend').on('click', function (e) {
    $('.progress').show()
    var data = $(this).data()
    $.ajax({                       
        url: data.sortUrl,                    
        data: {
            'cat': data.cats,
            'gender': data.gen,     
        },
        success: function (data) {   
            $('#products').html(data);  
        }
    });
    $('.progress').hide()
});
</script>

Product/templates/Product/prodcat.html
{% extends 'home/base.html'%}
{% load static from staticfiles%}

<!--<div class="row isotope-grid">
				{% for pro in product %}
				<div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item {{pro.categories}}">
				
					<div class="block2">
						<div class="block2-pic hov-img0">
							<img src="{{pro.prod_image.url}}" alt="IMG-PRODUCT">

							<a href="{% url 'detail' pro.pk %}" class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 ">
								Quick View
							</a>
						</div>

						<div class="block2-txt flex-w flex-t p-t-14">
							<div class="block2-txt-child1 flex-col-l ">
								<a href="{% url 'detail' pro.pk %}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
									{{pro.name}}
								</a>

								<span class="stext-105 cl3">
									{{pro.price}}
								</span>
							</div>

							<div class="block2-txt-child2 flex-r p-t-3">
								<a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
									<img class="icon-heart1 dis-block trans-04" src="{% static  'efe/images/icons/icon-heart-01.png' %}" alt="ICON">
									<img class="icon-heart2 dis-block trans-04 ab-t-l" src="{% static  'efe/images/icons/icon-heart-02.png' %}" alt="ICON">
								</a>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>-->
{% block content %}

<div style="padding-bottom:10px;">
	<img class="img-responsive"  src="{{category.shelve.url}}">
</div>

<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8 pos">
		<div class="col-sm-12">
		{% for gen in gender %}	
		<div class="col-sm-6 col-xs-6">
			
			<div class="boxs"><a href="{% url 'Home:categories' pk=gen.pk cat=category.pk  %}">
			<img class="img-responsive " src="{{gen.gender_image.url}}">
			 <h4 class="top-left">{{gen.gender}}</h4></a>
			</div>
			
		</div>
		{% endfor %}
		</div>

	</div>
	<div class="col-sm-2"></div>
</div>

{% endblock %}

Product/templates/Product/product.html
{% extends 'home/base.html'%}
{% load crispy_forms_tags %}
{% load static from staticfiles%}
{% block content %}
 
<nav>
  <ol class="breadcrumb" style="background-color: orange" >
    <li class="breadcrumb-item"><a href="{% url 'Home:index' %} ">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'Home:Gender' pk=product.gender.pk %}">{{product.gender.gender}}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'Home:category' pk=product.categories.pk %}">{{product.categories.catname}}</a></li>
    <li class="breadcrumb-item active">{{product.prodname}}</li>
  </ol>
  
</nav>
<div class="row" style="background-color: #eeeeee; margin-bottom: 2%;  ">
    <div class="container" style="margin-top:5%; margin-bottom: 5%" >
      <div class="row">
        <div class="col-md-2 col-xs-4">
          <div class="col-md-12 col-xs-12" id="thumbs">

            <a href="{{product.prod_image.url}}" class="images" data-img="{{product.prod_image.url}}"  ><img src="{{product.prod_image.url}}" class="thumbnail img-responsive" style="  margin-bottom: 5%;"></a><br>
            <a href="{{product.frontImage.url}}" class="images" data-img="{{product.frontImage.url}}"><img src="{{product.frontImage.url}}" class="thumbnail img-responsive" style="  margin-bottom: 5%;"></a><br>
            <a href="{{product.rearImage.url}}" class="images" data-img="{{product.rearImage.url}}" ><img src="{{product.rearImage.url}}" class="thumbnail img-responsive" style="  margin-bottom: 5%;"></a><br>
          </div>
        </div>
        <div class="col-md-6 col-xs-8">
          <img id="imgs" src="{{product.prod_image.url}}" class="img-thumbnail img-responsive" style=" width: 90%; height: 80%;">
        </div>
        <div class="col-xs-3"></div>
        <div class="col-md-4 col-xs-7">
            <h3>{{product.prodname}}</h3>
            <h4>{{product.price}}</h4>
            <p>{{ product.description|safe|linebreaksbr }}</p>
            <form class="form-horizontal" action="{% url 'cart:cart_add' product.id %}" method="post">
              {% csrf_token %}
              <div class="form-group">
              {{ item.sizes|as_crispy_field}}
              {{ item.quantity|as_crispy_field}}
              <div>
              {{ item.update|as_crispy_field}}
                <center><button type="submit" class="btn btn-danger btn-md">Add to Basket</button></center>
              </div>          
            </form>
        </div>
      </div>
    </div> 
</div>
{% endblock %}
{% block javascript%}
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>    
<script type="text/javascript">
$('#thumbs').on('click', 'a', function(event) {
  $('#imgs').attr('src', this.href);

  return false;
});
</script>
{%endblock %}